### ISSUE TITLE
Spacepy is impossible to install from pip with either gfortran >= 8 or numpy>=1.16 or both

### ISSUE THREAD

**Issue by asreimer** [spacepy/spacepy#108] opened 2019-03-15 09:26 UTC
## The Error
When trying to install spacepy via pip (`pip install spacepy`), I get the following error:

        subprocess.CalledProcessError: Command '['f2py', '--overwrite-signature', '-m', 'irbempylib', '-h', 'irbempylib.pyf', 'source/onera_desp_lib.f', 'source/CoordTrans.f', 'source/AE8_AP8.f', 'source/find_foot.f', 'source/drift_bounce_orbit.f', 'only:', 'make_lstar1', 'make_lstar_shell_splitting1', 'find_foot_point1', 'coord_trans1', 'find_magequator1', 'find_mirror_point1', 'get_field1', 'get_ae8_ap8_flux', 'fly_in_nasa_aeap1', 'trace_field_line2_1', 'trace_field_line_towards_earth1', 'trace_drift_bounce_orbit', ':']' returned non-zero exit status 1.
        
        ----------------------------------------
    Command "/opt/conda/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-x9hbva8s/spacepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext install --record /tmp/pip-record-z1bgs_z0/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-x9hbva8s/spacepy/

This only happens for `spacepy==0.1.6`. No error for `spacepy==0.1.5`.

This seems like it is due to the recent change in the newer versions of gfortran and how it now by default enforces modern fortran syntax, requiring a `--std=legacy` flag to be set to properly compile legacy code. This is explained nicely [here](https://www.scivision.co/gcc-gfortran-std-legacy/). This is related to the problem that spacepy recently had with numpy 1.16 which was fixed (https://github.com/spacepy/spacepy/pull/106) by removing non-standard fortran comments.

So that means that it is currently impossible to install spacepy from pip if you have `numpy >= 1.16`. The same error happens if you have `numpy < 1.16` installed but `gfortran >= 8`.

Normally, one can work around this by passing additional build options to pip. This doesn't work for spacepy because spacepy has hardcoded all of the f2py options and doesn't grab additional flags passed in. For example, one can usually do something like:

    F77FLAGS='--std=legacy' pip install --global-option='build_ext' <package name>

To verify that passing `--std=legacy` to f2py would have fixed the problem, I pulled the `release-0.1.6` tag and tried to install with `pip install .` and it failed with the same message as reported above. I then modified the setup.py and added `"--std=legacy"` into [this line](https://github.com/spacepy/spacepy/blob/release-0.1.6/setup.py#L411) and was able to successfully build and install spacepy.

I see that spacepy fixed the non-standard fortran comments causing this problem with https://github.com/spacepy/spacepy/pull/106 (I pulled the master branch and installed successfully with `pip install .` to verify), so the `--std=legacy` thing won't be needed if the commit that fixed this is pushed to PyPi.

## Possible Solutions
There are 3 possible solutions:
1) Spacepy installs fine with https://github.com/spacepy/spacepy/pull/106, so if spacepy made a 0.1.7 release and published it to PyPi, that would resolve this, or
2) Spacepy checks for the `F77FLAGS` environment variable and appends them to the f2py command [here](https://github.com/spacepy/spacepy/blob/release-0.1.6/setup.py#L411) and other places the f2py is invoked for f77 code (or use a catch all `FFLAGS` for all f2py calls), or
3) Expect the user to use the git master branch.

Please let me know what is decided. I'm trying to use spacepy for a project. For now I'll probably clone [this](https://github.com/spacepy/spacepy/commit/8b8c2d56ebdcb1d3a59fd868a1c92f34ce16ec64) master branch commit.

I tried to be thorough; let me know if there's additional information you need from me.

**Comment by jtniehof** [comment] 2019-03-15 15:20
Thanks for the detailed writeup. Just to be clear, installing from master works right now? In that case we're in pretty good shape and people who are comfortable running off master can install with pip:
`pip install git+https://github.com/spacepy/spacepy.git`

And then we'll sweep things up in the next release (and probably close this in the meantime.)

I want to pull the thread on the environment variables a bit, since that may be an enhancement worth making (and I'll open another issue based on the answers here.) There are several different issues. One is that the spacepy setup hardcodes the Fortran compiler options to build the irbem library itself. That's sort of a function of knowing how to build the library. Then there are the f2py flags, which are a combination of hardcoded for what needs to be done for compatibility with the irbem build and pass-throughs of a few of the main options. And finally there's environment variables, which the spacepy setup does not step on. In fact, if LDFLAGS is set, f2py behaves differently and the installer specifically adds back in the necessary options. Basically the flags actually passed to the compiler are those set up by numpy's distutils support.

What I'd like to get at is what's the expected behavior, why is that expected, and then we can craft an enhancement plan to hit it.

1. Is there an expectation that spacepy will check for various environment variables and translate those into command line options for f2py? Is there some place where this sort of expectation is documented?
2. Is there an expectation that spacepy will translate certain environment variables into command line options for the Fortran compilers while building the irbem lib (i.e. non-f2py fortran calls), and is there some list for this? The spacepy installer isn't trying to duplicate GNU autotools behavior. But we can, for example, be more aggressive about querying flags from the numpy distutils support and applying those to the baseline irbem build.
3. Is there an expectation that the build command for setup.py will accept all f2py command line options and pass them through?
4. Is there an expectation that f2py will behave in certain ways when certain environment variables are set, and the spacepy installer is doing something that is inhibiting this behavior? (Are these documented?)

The goal here is to support cases where the person installing spacepy knows more about their fortran compiler or system setup and wants to provide appropriate hints to make things happen, without having huge gobs of code that just copies a list of environment variables into command line options. And still meet the top-level goal of it "just working" in most situations, of course.

**Comment by balarsen** [comment] 2019-03-15 16:01
From my point of view:
3. Is there an expectation that the build command for setup.py will accept all f2py command line options and pass them through?

I was trying to install the other day on a new machine and was too lazy to get the gfortran all setup. I wanted to pass `--fcompiler=none` through to setup.py but could not make this work using pip and fell back to clone and `python setup.py install --fcompiler=None`. 

One for the wish list.

**Comment by asreimer** [comment] 2019-03-15 19:56
@jtniehof In my opinion the problem is that spacepy 0.1.6 is effectively a broken release for users with the latest numpy or gfortran 8. And expecting users to run off of master is fine, except what is master? As soon as a dev makes a new commit to master, the master I have and the master another user has are not the same. It could get messy for devs and users. Ideally, 1 is the best possible solution for everyone, except it requires some dev time to roll the new release and I understand that there may not be an abundance of that.

> In fact, if LDFLAGS is set, f2py behaves differently and the installer specifically adds back in the necessary options.

`LDFLAGS` is supposed to be used for passing flags to the linker, so if spacepy is using it to pass args to f2py that's probably not a proper usage. Furthermore, trying:

    LDFLAGS='--std=legacy' pip install --global-option='build_ext' .

doesn't work, I get the error message:

    subprocess.CalledProcessError: Command '['f2py2.7', '--overwrite-signature', '-m', 'irbempylib', '-h', 'irbempylib.pyf', 'source/onera_desp_lib.f', 'source/CoordTrans.f', 'source/AE8_AP8.f', 'source/find_foot.f', 'source/drift_bounce_orbit.f', 'only:', 'make_lstar1', 'make_lstar_shell_splitting1', 'find_foot_point1', 'coord_trans1', 'find_magequator1', 'find_mirror_point1', 'get_field1', 'get_ae8_ap8_flux', 'fly_in_nasa_aeap1', 'trace_field_line2_1', 'trace_field_line_towards_earth1', 'trace_drift_bounce_orbit', ':']' returned non-zero exit status 1

in which you can see that there is no `--std=legacy` so I don't see the `LDFLAGS` getting passed in to f2py.

Responding to your numbered list:
1) No, I think the expectation is that options for f2py are not hard coded in. For example, using `numpy` allows the extensions to be built without using the `subprocess` call that spacepy is currently using. Use `numpy.distutils.core import Extension, setup` for this without calling f2py with a subprocess call.
2) This is related to 1). The fact that spacepy hard codes specific subprocess calls for f2py is causing the problem here. You can pass a bunch of flags to f2py via pip's `--global-option` flag and numpy will handle all of this for you if you use the distutils setup.
3) and 4: Yes, but this comes for free if you don't hard code things and end-run around numpy's distutils.

Looking more at the [setup.py file here](https://github.com/spacepy/spacepy/blob/release-0.1.6/setup.py#L24) I see that spacepy isn't using the `Extension` class from numpy. I understand why the subprocess calls are needed. If spacepy uses the Extension class, it doesn't need subprocess.


@balarsen You can do:

    pip install --global-option='build_ext' --global-option='--fcompiler=None' <package name>

**Comment by asreimer** [comment] 2019-03-20 17:48
If it's helpful, here's a clean example of a `setup.py` that uses the `numpy.distutils.core.Extension` class without a hardcoded calls to f2py via subprocess: https://github.com/aburrell/apexpy/blob/master/setup.py

With this, you can pass LDFLAGS, FFLAGS, etc. environment variables, all without having to add any code to handle them specifically.

**Comment by drsteve** [comment] 2019-03-21 20:45
Just to follow up on this (mostly as a summary for folks browsing the issues).

Thanks @asreimer for the report and for the discussion. The short answer to your initial question is that we are aiming to have a 0.1.7 release soon, which would completely address this issue as the underlying incompatibility has been addressed already. In the interim, I would recommend building from master.

There's the additional issue of cleaning up our setup. Again, thanks for the input. It will help with a targeted clean-up. Since this was written there has been an incredible evolution of the build and distribution tools for Python - revising a system that still worked wasn't a priority, especially given the rapid pace of changes to the build and packaging systems. The recent changes to gfortran and f2py that led to a breakage obviously made this more important.

So, to give a response to each of your possible solutions:
 - Spacepy installs fine with #106, so if spacepy made a 0.1.7 release and published it to PyPi, that would resolve this : *Building a 0.1.7 release is our current priority*
 - Spacepy checks for the F77FLAGS environment variable and appends them to the f2py command here and other places the f2py is invoked for f77 code (or use a catch all FFLAGS for all f2py calls) : *Revision of the build system is warranted, but we do not expect users to have to set additional flags to build spacepy*
- Expect the user to use the git master branch : *There is no expectation that users will install from the git repo. However, users on many systems won't have gcc 8 yet, and it's difficult to expect an old release to be forward-compatible for too long. I'd encourage anyone comfortable with doing so to use the master branch of the git repo. pip-installable releases are essential and should **just work**, and preparation of 0.1.7 is already underway.*

This issue should probably be closed since it's essentially a comment on the forward compatibility of an old release; the current master doesn't have this issue and the new release is being worked on. It'll be up on pip as soon as we clear up some final issues that are already on the board for that release version. We should probably take this issue as motivation to accelerate the release where possible and decide whether some of the outstanding issues can wait.

If there's no objection I'll probably close this issue early next week and we can use it as a resource when revising the build.

I'd also like to encourage anyone interested in contributing updates to do so. Core developer time is limited and feedback always helps focus attention where users need it most. Patches to address any particular issue are always welcome. Our preferred workflow is to fork the repo, make the appropriate changes, then send a pull request. We'll review the PR and, after any required discussion and updates, pull that into master.

**Comment by jtniehof** [comment] 2019-03-21 20:50
My plan is to spin this out into two enhancement requests: one for looking into using numpy distutils more heavily for the f2py build, and one for more general ability to pass things through to f2py (which might be superseded, but I think they are potentially separate issues.) I'll copy over the relevant information from this discussion (actually the pip option-passing is something we should capture in the docs, too). And then close this. Both of those enhancement requests would be a post-next-release thing.

Sorry, my spacepy time has been very limited lately.

**Comment by drsteve** [comment] 2019-03-26 01:05
Closing in line with comments above.
@jtniehof can you refer to this issue when you file the spin-off issues?

Thanks.

**Closed by drsteve** 2019-03-26 01:05 UTC

**Comment by asreimer** [comment] 2019-03-27 20:22
@drsteve sounds good!

Just one semi-nasty thing that, from a user point of view, happens when users are encouraged to cherrypick commits from the master branch, importing spacepy results in:

    This unreleased version of SpacePy is not supported by the SpacePy team.

which I thought was a bit humorous. It reiterates the "It could get messy for devs and users" comment I made originally :)

Totally understand that this is probably moot for most people and will be moot once 0.1.7 is out. Cheers.

**Comment by jtniehof** [comment] 2019-03-27 20:45
Yep, ideally we'd rather people not work off master if possible. We'd very much rather people not clone master and distribute it as if it were a release. A non-hypothetical that resulted in that message. We definitely do aim for releases being more polished than master.

But if people have specific problems that we think are fixed in master, we do appreciate them jumping in and letting us know how it works out.
