### ISSUE TITLE
pycdf deprication warning on float

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#224] opened 2019-10-18 20:32 UTC
There are a couple deprecation warnings in pycdf

1. Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`
1. Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated.

```
python test_pycdf_istp.py
......./Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:1671: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[postidx]
..../Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:1671: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[postidx]
............./Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:1671: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[postidx]
./Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:1671: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[postidx]
.........../Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:302: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if numpy.issubdtype(v.dtype, numpy.float):
../Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/__init__.py:1196: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif numpy.issubdtype(dtype, numpy.float):
..........
----------------------------------------------------------------------
Ran 48 tests in 2.069s

OK
```

Darwin-18.6.0-x86_64-i386-64bit
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
numpy=1.17.3
scipy=1.3.1
matplotlib=3.1.1

oops I am running spacepy
0931b448f0945ecb4b7878fc170ddc873f2db3ca (HEAD -> jtniehof-pycdf-istp-bundle, origin/pycdf-istp-bundle)

But the issue is the same.

**Comment by jtniehof** [comment] 2019-10-18 20:55
Well, some of those are on the branch that isn't merged, so not an issue yet ;) I'll discuss on #222 for that. The other shouldn't be bad.

**Comment by jtniehof** [comment] 2019-10-18 21:31
Aha, part of the problem is that get_minmax doesn't have direct unit tests (only tested through tests in pycdf_istp) so that sort of hides that particular deprecation. Will fix that as well.

**Comment by jtniehof** [comment] 2019-10-21 15:10
#222 and #225 combined fix this one.

**Closed by jtniehof** 2019-10-21 15:10 UTC
