### ISSUE TITLE
Issue installing/compiling IRBEMlib

### ISSUE THREAD

**Issue by grimcreeper97** [spacepy/spacepy#190] opened 2019-08-05 20:19 UTC
Greetings.

When trying to install Spacepy on OS X, it fails when trying to compile IRBEMlib.
Note that all requisites were installed via MacPorts.

### Minimal example to reproduce issue:
```
python setup.py build
```

### Error message/Traceback:
```
running build
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running build_py
customize Gnu95FCompiler
Found executable /opt/local/bin/gfortran
Found executable /opt/local/bin/ar
Found executable /opt/local/bin/ranlib
Reading fortran codes...
        Reading file 'source/onera_desp_lib.f' (format:fix,strict)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/fortran_version.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/fortran_release.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/ntime_max.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/variables.inc' (format:fix)
        Reading file 'source/ntime_max.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
Traceback (most recent call last):
  File "/opt/local/bin/f2py", line 11, in <module>
    load_entry_point('numpy==1.16.4', 'console_scripts', 'f2py')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 685, in main
    run_main(sys.argv[1:])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 361, in readfortrancode
    l = fin.readline()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 299, in readline
    line = self._readline()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2693: ordinal not in range(128)
Traceback (most recent call last):
  File "setup.py", line 1001, in <module>
    setup(**setup_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 772, in run
    self.compile_irbempy()
  File "setup.py", line 524, in compile_irbempy
    subprocess.check_call(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['f2py', '--overwrite-signature', '-m', 'irbempylib', '-h', 'irbempylib.pyf', 'source/onera_desp_lib.f', 'source/CoordTrans.f', 'source/AE8_AP8.f', 'source/find_foot.f', 'source/drift_bounce_orbit.f', 'only:', 'make_lstar1', 'make_lstar_shell_splitting1', 'find_foot_point1', 'coord_trans1', 'find_magequator1', 'find_mirror_point1', 'get_field1', 'get_ae8_ap8_flux', 'fly_in_nasa_aeap1', 'trace_field_line2_1', 'trace_field_line_towards_earth1', 'trace_drift_bounce_orbit', ':']' returned non-zero exit status 1.
```

We dug into this further by seeing what the installer is failing to achieve by pasting the above command into a terminal window:

```
f2py --overwrite-signature -m irbempylib -h irbempylib.pyf source/onera_desp_lib.f source/CoordTrans.f source/AE8_AP8.f source/find_foot.f source/drift_bounce_orbit.f only: make_lstar1 make_lstar_shell_splitting1 find_foot_point1 coord_trans1 find_magequator1 find_mirror_point1 get_field1 get_ae8_ap8_flux fly_in_nasa_aeap1 trace_field_line2_1 trace_field_line_towards_earth1 trace_drift_bounce_orbit :
```

...which yields the following:

```
Reading fortran codes...
        Reading file 'source/onera_desp_lib.f' (format:fix,strict)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/fortran_version.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/fortran_release.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/ntime_max.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
        Reading file 'source/variables.inc' (format:fix)
        Reading file 'source/ntime_max.inc' (format:fix)
        Reading file 'source/wrappers.inc' (format:fix)
Traceback (most recent call last):
  File "/opt/local/bin/f2py", line 11, in <module>
    load_entry_point('numpy==1.16.4', 'console_scripts', 'f2py')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 685, in main
    run_main(sys.argv[1:])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 361, in readfortrancode
    l = fin.readline()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 299, in readline
    line = self._readline()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2693: ordinal not in range(128)
```

I cannot determine what is going on with the ascii issue listed above. Any help or suggestions would be greatly appreciated.

### OS, Python version, and dependency version information:
Darwin-18.7.0-x86_64-i386-64bit
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
numpy=1.16.4
scipy=1.3.0
matplotlib=3.1.1

**Comment by jtniehof** [comment] 2019-08-05 21:24
Can you confirm you're using SpacePy 0.2.0? This looks a lot like something that's cropped up in the past.

**Comment by grimcreeper97** [comment] 2019-08-06 00:31
I currently have SpacePy 0.1.6

**Comment by jtniehof** [comment] 2019-08-06 12:11
That's probably the issue. Can you grab 0.2.0 from [github](https://github.com/spacepy/spacepy/releases/tag/release-0.2.0) or [PyPI](https://pypi.org/project/spacepy/#files) and try that? The .tar.gz should be the right one for you. (This is also what would be downloaded if you `pip install spacepy` if you prefer that.)

**Comment by grimcreeper97** [comment] 2019-08-06 20:51
Downloaded and installed the .tar.gz file for version 0.2.0 and get back the same error message. The development source code doesn't work either.

**Comment by jtniehof** [comment] 2019-08-07 17:29
Thanks. I have a suspicion. In your uncompressed source directory, can you edit `spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/onera_desp_lib.f`, go to line 331, and remove the likely unprintable character there? You should wind up with something like:
`
c Compute Bmin assuming 90 PA at S/C
`
Then try the build again. I suspect we have a regression here.

**Comment by jtniehof** [comment] 2019-08-07 17:36
(Suspicion is this is a regression from 63e2d6a39c5dfcbfe77d4c552eae2efefb1b4246)

**Comment by drsteve** [comment] 2019-08-07 18:00
Looks like it crept back in at ae71cf0 (which would make it my fault).
Odd that it passes testing on most systems and configurations though.

**Comment by jtniehof** [comment] 2019-08-07 18:12
I think that's what we were seeing last time, too: only broken on some systems. If this works out on @grimcreeper97 's system we can add it to your irbem update checklist and hopefully not have it bite us again.

I'm working on getting set with a Mac so I can support these system-specific things better but it might be a bit.

**Comment by drsteve** [comment] 2019-08-07 18:27
The regression means I didn't push the change upstream to IRBEM. That'd be the easiest way of preventing any future regressions on update of the IRBEM code.
Changing the degree symbols is listed in the IRBEM update notes already, but the line numbers are out of date. Those used to break on my various local test environments, so I guess I missed it (and it passes on all of our Travis environments as well as our Windows test environments).

Proposed fix:
- Remove the unicode degree symbols from `onera_desp_lib.f` in our codebase
- Make same change in IRBEMlib repo (assigned to me since I have commit access)

**Comment by grimcreeper97** [comment] 2019-08-07 19:17
After removing the unprintable characters line lines 331 and 3083; I re-installed and re-built and didn't receive my initial error. I'll keep you both updated if anything else shows up.

**Comment by jtniehof** [comment] 2019-08-07 19:35
Excellent! Thanks for trying it out.

**Closed** 2019-08-07 22:00 UTC
