### ISSUE TITLE
pip install stalls for python 2.7

### ISSUE THREAD

**Issue by jslavin** [spacepy/spacepy#24] opened 2018-09-18 13:24 UTC
I was using spacepy back in July with no problem and installed it via pip.  I recently ran into a problem with my anaconda install and decided to do a fresh install.  Now installing with pip to a python 2.7 distribution doesn't work (it does work for python 3.6).  It gets to the point:
Building wheels for collected packages: spacepy
  Running setup.py bdist_wheel for spacepy ...
And then just sits there.  Anyone have suggestions on this?

Jon

**Comment by drsteve** [comment] 2018-09-18 17:52
Thanks @jslavin 
Assuming that you're just doing a straight pip install spacepy, so pulling from PyPI instead of a custom source (like github), then I'm really not sure. The version on PyPI hasn't been updated for a while, so my guess is that the issue is probably something to do with either pip, numpy.distutils or setuptools.

I'm also unable to reproduce. On a Red Hat Enterprise linux system (with Python 2.7) I seem to hit an ```ffnet``` build error, but installing spacepy with ```pip install spacepy --user --no-deps --ignore-installed``` works. That's true for both my regular environment and a clean virtualenv.

On my standard machine (Kubuntu 16.04LTS) I can install from pip (for Python 2.7) using either ```pip install spacepy --user --no-deps``` (which would avoid any ffnet issues, and uses whatever random versions of dependencies I had installed) or ```pip install spacepy --user --ignore-installed``` (which basically forces everything to be reinstalled, even if the dependencies are already met).

Can you  let us know the output from
```
pip --version
python -c "import numpy; print(numpy.version.version)"
python -c "import setuptools; print(setuptools.__version__)"
```
along with your OS version?

Thanks,
Steve

**Comment by jslavin** [comment] 2018-09-18 18:11
Yes I just did pip install spacepy.  That was with conda in a 2.7 environment. I'm running CentOS 7.
> pip --version
pip 18.0 from /export/slavin/anaconda/envs/py2/lib/python2.7/site-packages/pip (python 2.7)
> python -c "import numpy; print(numpy.version.version)"
1.15.0
> python -c "import setuptools; print(setuptools.__version__)"
40.2.0

I actually solved my problem by just copying over my spacepy directory from my old anaconda install to the new one.  Still it would be nice to understand why pip install didn't work.  I believe that's how I installed it before.  I also tried downloading the code from github and doing "python setup.py build". I used --fcompiler=gnu95.  I ended up getting a bunch of errors related to implied do-lists and in the end it hung.  After killing it I got the message:
setup produced the following warnings. Some functionality may be missing.

irbemlib module failed. Try a different Fortran compiler? (--fcompiler)
irbemlib build produced no recognizable module. Try a different Fortran compiler? (--fcompiler)

I also tried with an Intel fortran compiler, also without success. That time it stopped apparently while compiling fortranobject.c

Jon

**Comment by drsteve** [comment] 2018-09-19 02:42
I'll see if I can find a CentOS 7 system to test on. I'll leave this open until then. If I can't reproduce the error then I'll close the issue.

I'm glad you've got things working again, but it's definitely not how things are *supposed* to work. Ideally ```pip``` should just work. For reference, the Fortran warnings are sadly expected from the bundled IRBEM library, but they're not fatal.

@balarsen, you run CentOS on some machines? Can I ask you to try to reproduce this?

**Comment by balarsen** [comment] 2018-09-19 13:04
I’m off on vacation for a week but I can try upon my return.

**Comment by jtniehof** [comment] 2018-09-21 16:10
@drsteve, you were saying you were having problems with the Travis build hanging on 2.7. Could this be related?

**Comment by drsteve** [comment] 2018-09-21 16:36
It could be.
The hang came at:
```
	Wrote C/API module "irbempylib" to file "/tmp/tmpaeAmO3/src.linux-x86_64-2.7/irbempylibmodule.c"
	Fortran 77 wrappers are saved to "/tmp/tmpaeAmO3/src.linux-x86_64-2.7/irbempylib-f2pywrappers.f"
  adding '/tmp/tmpaeAmO3/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding '/tmp/tmpaeAmO3/src.linux-x86_64-2.7' to include_dirs.
copying /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmpaeAmO3/src.linux-x86_64-2.7
copying /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.h -> /tmp/tmpaeAmO3/src.linux-x86_64-2.7
  adding '/tmp/tmpaeAmO3/src.linux-x86_64-2.7/irbempylib-f2pywrappers.f' to sources.
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler using build_ext
building 'irbempylib' extension
compiling C sources
C compiler: gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
creating /tmp/tmpaeAmO3/tmp
creating /tmp/tmpaeAmO3/tmp/tmpaeAmO3
creating /tmp/tmpaeAmO3/tmp/tmpaeAmO3/src.linux-x86_64-2.7
compile options: '-I/tmp/tmpaeAmO3/src.linux-x86_64-2.7 -I/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/numpy/core/include -I/opt/python/2.7.14/include/python2.7 -c'
gcc: /tmp/tmpaeAmO3/src.linux-x86_64-2.7/fortranobject.c
gcc: /tmp/tmpaeAmO3/src.linux-x86_64-2.7/irbempylibmodule.c
```
See [https://travis-ci.com/drsteve/spacepy/jobs/137200999](https://travis-ci.com/drsteve/spacepy/jobs/137200999)

I've never seen it hang on building a wheel, and I haven't been able to reproduce the hang outside of Travis...

**Comment by jtniehof** [comment] 2018-09-27 19:56
@jslavin , are you able to upgrade to numpy 1.15.1 and try again? it's working in Anaconda on Windows with that numpy.

**Comment by jslavin** [comment] 2018-09-27 20:19
I could try, though as I mentioned I now have it working (by copying it from my old install).

**Comment by drsteve** [comment] 2018-09-27 23:10
The stall I was getting in Travis for Python 2.7 (#30) is no longer happening, the latest numpy is 1.15.2 and the hang I was getting was on 1.15.0, before 1.15.1 had released. I also have no hangs on Python 2.7 with older versions of numpy.

It really looks like numpy 1.15.0 is the culprit and @jtniehof pointed out in #30 
I'll leave this open for a few more days and then close unless someone can identify a different reason for this failure.

**Comment by drsteve** [comment] 2018-10-09 23:37
Closing as solved.

The ```README.md``` now lists numpy 1.15.0 as a specific exclusion. Issue #38 has discussion on pip installation which is where we'll need to ensure that this specific version of numpy doesn't get used.

**Closed by drsteve** 2018-10-09 23:37 UTC
