### ISSUE TITLE
spacepy.irbempy import error

### ISSUE THREAD

**Issue by evandegriff** [spacepy/spacepy#585] opened 2022-03-17 20:23 UTC
I am getting an import error when trying to use spacepy.irbempy (seems to be the same as in [#535](https://github.com/spacepy/spacepy/issues/535))

### Minimal example to reproduce issue:

I first cloned the spacepy git repository using

```
git clone https://github.com/spacepy/spacepy.git
```
I then ran the following command to install:

```
python setup.py install --user 2>&1 | tee diagnostics.txt
```

Here is the [diagnostics.txt](https://github.com/spacepy/spacepy/files/8290058/diagnostics.txt) file output from the install. 
After installing, I run Python 3.9 and attempt to import spacepy.irbempy and get the following error.

### Error message/Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/exv3640/myscripts/spacepy/spacepy/irbempy/__init__.py", line 71, in <module>
    from .irbempy import *
  File "/Users/exv3640/myscripts/spacepy/spacepy/irbempy/irbempy.py", line 30, in <module>
    from . import irbempylib as oplib
ImportError: cannot import name 'irbempylib' from partially initialized module 'spacepy.irbempy' (most likely due to a circular import) (/Users/exv3640/myscripts/spacepy/spacepy/irbempy/__init__.py)
```

Unlike #535, I am using MacPorts to install python.

Fyi, @spacecataz can also reproduce this error.

### OS, Python version, and dependency version information:

```
macOS-11.6.4-x86_64-i386-64bit
sys.version_info(major=3, minor=9, micro=10, releaselevel='final', serial=0)
numpy=1.22.3
scipy=1.8.0
matplotlib=3.5.1
```

### Version of SpacePy

I downloaded spacepy version 0.2.3 from GitHub

**Comment by spacecataz** [comment] 2022-03-17 20:34
Some more info- this may be a Macports issue, as the behavior popped up on recent updates to Macports (version 2.7.2). Everything worked fine for both of us until we updated Macports and associated ports. Haven't been able to pin down the differences yet...

**Comment by spacecataz** [comment] 2022-03-17 21:19
Reproducing this on my own machine and have now determined what is happening. If you call the build step independently, ie., 

``` 
python setup.py build
python setup.py install --user
```

and then install, everything is fine. This is new behavior with the updates to MacPorts: without updating my spacepy source code, the build step happened when the install step was called. Removing `build` and `dist` does not change this behavior.

@evandegriff was able to reproduce this issue using Python 3.10 and 3.7, I believe.

There are obfuscating issues here. Since updating MacPorts, we are having issues with the PYTHONPATH. If we do not explicitly include the user-level `site-packages` folder in PYTHONPATH, we get warnings on install and cannot import. I've been looking into this and there's some very weird new behavior. The degree to which that is related to this issue is not clear to me at this time. Note the warnings at the top of diagnostics.txt file in the original post.

This may be a MacPorts issue, but I'm not seeing any similar issues on their tracker.

**Comment by evandegriff** [comment] 2022-03-18 18:30
I can reproduce this workaround solution in Python 3.9 with spacepy 0.2.3, if I use

```
python setup.py build
sudo python setup.py install
```
spacepy imports correctly and there are no spacepy.irbempy import errors.

> Reproducing this on my own machine and have now determined what is happening. If you call the build step independently, ie.,
> 
> ```
> python setup.py build
> python setup.py install --user
> ```
> 
> and then install, everything is fine. This is new behavior with the updates to MacPorts: without updating my spacepy source code, the build step happened when the install step was called. Removing `build` and `dist` does not change this behavior.
> 
> @evandegriff was able to reproduce this issue using Python 3.10 and 3.7, I believe.
> 
> There are obfuscating issues here. Since updating MacPorts, we are having issues with the PYTHONPATH. If we do not explicitly include the user-level `site-packages` folder in PYTHONPATH, we get warnings on install and cannot import. I've been looking into this and there's some very weird new behavior. The degree to which that is related to this issue is not clear to me at this time. Note the warnings at the top of diagnostics.txt file in the original post.
> 
> This may be a MacPorts issue, but I'm not seeing any similar issues on their tracker.
> 
> EDIT: Since updating Macports, we cannot get a successful install via the `--user` flag.

**Comment by drsteve** [comment] 2022-03-18 19:09
This is quite weird, and I can't test as I don't have access to a mac, but... last time this was brought up the only way I could trigger the same error was by supplying `--user` in an anaconda environment (where `--user` is contraindicated). 

Obviously you're not using anaconda here, but most of the anaconda (or venv) magic is changing paths. And as noted here, the pathing is not as expected, but also is reported as an issue right at the top of the diagnostics... my question would be whether this is something that can/would happen with other python packages (I guess it'd be more likely with bigger and more complex packages), or whether it's specific to our package structure and/or build scripts. I'm not sure how easy that question is to answer, so please consider this an open question rather than a directed question!

Depending on the answer to that question I might move this over to discussion. It's obviously going to be in everyone's interests to solve this and to have a solution available for when the next unlucky folks hit the problem, but my first reaction is that this is not a spacepy issue specifically, just an issue that's come to light with spacepy.

**Comment by drsteve** [comment] 2022-03-18 19:44
Can I ask someone to try installing with:
`python setup.py install --user --prefix=`
No whitespace after the last argument, just equals then enter.

I'm following a bad hunch that MacPorts might've added a hidden global configuration... (e.g., https://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install)

**Comment by evandegriff** [comment] 2022-03-18 20:19
I have tried the above install command, and also tried it with the build step first, as below:
```
python setup.py build
python setup.py install --user --prefix=
```
in both cases, I could not import spacepy when opening up python.

To answer your earlier questions, I have not seen this happen with other packages so far but I will be on the lookout.

**Comment by drsteve** [comment] 2022-03-18 20:32
Do you know whether the install started with the same warnings, like 
> Checking .pth file support

and
>You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

And where did that install spacepy to? (should be plastered all over the install output)
At least on linux the standard place for that would be `~/.local/lib/python3.8/site-packages`, but I'm curious what is happening on the install here.
So assuming it can't import spacepy _at all_ after that installation, what happens if you set the `PYTHONPATH` environment variable so it includes the install location? Will it import `spacepy.irbempy`? I'm wondering whether it's hitting the same weird "copy the codebase instead of installing properly" issue, or whether it's building and installing fine, just isn't in a place your python can find it.

**Comment by evandegriff** [comment] 2022-03-18 20:57
I have already put the install location (``` ~/Library/Python/3.9/lib/python3.9/site-packages/``` ) into my PYTHONPATH, which has taken away those those errors. So even with the install location in my PYTHONPATH I can't import spacepy.irbempy, and installing with ```python setup.py install --user --prefix=``` without using sudo on the install I can't even import spacepy after installing.

**Comment by jtniehof** [comment] 2022-09-07 21:27
Closing because 0.4.0 and #639 addresses most of the issues that should give rise to this. If not, the behavior is different enough that the notes from old versions will probably not help find the issue.

**Closed by jtniehof** 2022-09-07 21:27 UTC
