### ISSUE TITLE
Negative return values in irbempy (get_Lstar, get_Lm) are not documented

### ISSUE THREAD

**Issue by Rhyst223** [spacepy/spacepy#104] opened 2019-02-21 13:06 UTC
I am trying to use get_Lstar to calculate the Lstar for a magnetometer station in GDZ coordinates, but the function will not give me an Lstar value, and the returned Lm value is unphysical. Here is my code

### Minimal example to reproduce issue:

```
from spacepy.time import Ticktock
from spacepy.coordinates import Coords
from spacepy.irbempy import get_Lstar

t = Ticktock(success['Time'][0])
y = Coords([100,56.376,-96.3], 'GDZ', 'sph',units=['km','deg','deg'])
g=get_Lstar(t,y)
```
Here, we have `success['Time'][0] = Timestamp('2008-01-01 08:00:00')`

However, the output of the function is

```
{'Lm': array([[-6.44920639]]),
 'Lstar': array([[nan]]),
 'Bmirr': array([[56384.77608068]]),
 'Bmin': array([70.56354592]),
 'Xj': array([[15.20358754]]),
 'MLT': array([1.24258515])}
```

The function returns `nan` for whatever timestamp I put in, and the Lm value is always negative which is unphysical. I've looked at the source code for Coords and I believe the input coordinates are fine, so is there something else that's going wrong or have I made an input error?
### Error message/Traceback:

```

```

**Comment by drsteve** [comment] 2019-02-21 20:10
This is a documentation issue. IRBEMlib sometimes has negative return values by design, for both Lm and L*. Our documentation addresses calling the routines but we haven't explained the odd-looking return values that are possible.

From the IRBEMlib documentation:
"negative values for L* and Lm indicate that particles are not trapped i.e. cannot bounce whereas absolute values of L* and Lm tell which drift shells are concerned"

So what that means for Lm is that a particle observed at the starting location can't bounce without moving below the nominal atmospheric loss height (in the opposite hemisphere).

You can test this by moving up in altitude: once you get above about 330km the negative sign will go away (and the magnitude only varies slowly as a function of altitude, even across the sign change). I should also point out that the magnetic field model used can greatly affect the quantitative result. That's controlled with the extMag keyword argument.

I'm not going to close the issue, but I will rename it and mark it as a documentation deficiency.

**Comment by Rhyst223** [comment] 2019-03-07 08:22
Sorry to address this again, but when I use GDZ coordinates the value for L* is nan, no matter which magnetic field model I use

**Comment by jtniehof** [comment] 2019-03-07 11:41
Got an email with a comment that seems to have disappeared, but it can work with GDZ:

```
t = spacepy.time.Ticktock('2010-01-01')                     
c = spacepy.coordinates.Coords([18000, 0, 0], 'GDZ', 'sph', units=['km', 'deg', 'deg'], ticks=t)
spacepy.irbempy.get_Lstar(t, c)

{'Bmin': array([ 478.68537486]),
 'Bmirr': array([[ 479.43667342]]),
 'Lm': array([[ 3.96853544]]),
 'Lstar': array([[ 3.84761501]]),
 'MLT': array([ 23.6709399]),
 'Xj': array([[ 0.00232111]])}
```

**Comment by Rhyst223** [comment] 2019-03-07 13:46
Sorry I asked a question but realised I hadn't formulated it probably. Now that I've thought about it the question is: given just geodectic latitude and longitude, how can I find the corresponding mirror point so that Lm is returned positive. I tried `spacepy.irbempy.find_Bmirror` but that just attempts to give me a mirror point at the same coordinates, which will just give a negative Lm value again

**Comment by jtniehof** [comment] 2019-03-07 14:16
So given a northern hemisphere mirrior point, you want the southern hemisphere mirror point? Are you interested in the actual mirror point (including altitude, and the failure if the particle would be lost to the atmosphere instead of mirroring) or do you want the footpoint of the field line?

**Comment by Rhyst223** [comment] 2019-03-07 14:43
Sorry I think I’ve caused some confusion so I’ll explain what my overall goal is!

Basically, I have data at a ground based magnetometer station and I want to map out the geographic location into Lm, with regards to a number of magnetic field models. 

I thought this could be done using spacepy.irbempy.get_Lm using my GDZ coordinates with altitude set to 0km (so maps directly from the ground) but this returns the negative value for LM. 

Then I thought the find_Bmirror function would give me the coordinates with the mirror point when the Lm value becomes positive (ie I I’d it GDZ with alt = 0km and it would return alt = something like 300km)

So now I’m wondering, am I approaching his the wrong way entirely. And if so, is there anything in spacepy that can map out ground locations to L via specific magnetic field models?

**Comment by drsteve** [comment] 2019-03-11 17:28
So I think the misunderstanding may stem from a fairly common misunderstanding of just what McIlwain L is (and how it is calculated).

In a dipole field the motion of energetic charged particles is organized by the mirror magnetic field strength and the "L" value (basically, L can be shown to be a function of I - the 2nd adiabatic invariant - and Bm). L is trivial to calculate in a dipole field and it's easily described as the radial distance at which a dipole field line crosses the magnetic equator. This is not true for other field configurations, where L is neither a conserved quantity nor a measure of where the field line actually goes. 

So how is McIlwain L calculated? Well, the equation (see, for example, Roederer's book) contains I (a form of the 2nd invariant). I is calculated as an integral along the magnetic field line between the two mirror points. Remember that McIlwain L (and Bm, and I) is pitch-angle dependent - it's a *particle* quantity, not a field quantity. So to calculate L for a point on the ground the implication is that a particle would be able to mirror there.

Most codes account for the reality that bouncing particles will be lost if they mirror at loo low an altitude, due to atmospheric collisions. That height is typically taken around 100km. Hence McIlwain L is undefined below that (because the particle can't complete a bounce without being lost). IRBEM, and hence irbempy, will note that the particle *should* have been lost by adding the minus sign, but will still report the value of McIlwain L calculated ignoring things like the atmosphere and the surface of the Earth.

In short, the concept of L is not tremendously relevant on the ground, or in the absence of energetic charged particles. IRBEM will still calculate it for any given field, but adds the minus sign to warn the user.

Of course, that doesn't mean L doesn't get used in this situation. The real question is why the ground location needs to have an L assigned. If you're looking for a ground signature where you have in situ particle measurements, for example, then you'd want the footpoint locations along the orbit of your satellite. A dipole L might be useful as a rough guide to the magnetospheric region that it maps to, but again, it really depends on use. The reality is that McIlwain L is tied to particle motion within a given field configuration and hence is of limited meaning on the ground.

Practically speaking, you can just drop the minus sign from the irbempy output and use that as your McIlwain L (noting that any particles would've actually been lost) and that might get you what you want. In that case and "bad" values returned should indicate that the location maps to open field lines.

**Closed** 2019-09-30 21:10 UTC
Labels: documentation
