### ISSUE TITLE
NaN output of coordinate transformation

### ISSUE THREAD

**Issue by GaryQ-physics** [spacepy/spacepy#534] opened 2021-06-10 19:44 UTC
Coordinate transformations can yield NaN's for valid inputs. These NaN's can vanish if different coordinate systems are called in a different order.

#### Code
```
import spacepy.coordinates as sc
from spacepy.time import Ticktock

cvals = sc.Coords([[1., 2., 4.]], 'GSM', 'car')
cvals.ticks = Ticktock(['2002-02-02T12:00:00'], 'ISO')
newcoordSM  = cvals.convert('SM', 'car')
newcoordMAG = cvals.convert('MAG', 'car')

print(newcoordSM)
print(newcoordMAG)
```

#### STDOUT
```
Coords( [[nan, nan, nan]] , 'SM', 'car')
Coords( [[-1.3220586384469575, 2.4447256780888083, 3.643552842405472]] , 'MAG', 'car')
```

#### Code
```
import spacepy.coordinates as sc
from spacepy.time import Ticktock

cvals = sc.Coords([[1., 2., 4.]], 'GSM', 'car')
cvals.ticks = Ticktock(['2002-02-02T12:00:00'], 'ISO')
newcoordMAG = cvals.convert('MAG', 'car')
newcoordSM  = cvals.convert('SM', 'car')

print(newcoordMAG)
print(newcoordSM)
```

#### STDOUT
```
Coords( [[-1.3220586384469575, 2.4447256780888083, 3.643552842405472]] , 'MAG', 'car')
Coords( [[1.9299022474205807, 2.0, 3.643552842405472]] , 'SM', 'car')
```

### OS, Python version, and dependency version information:
```
Linux-5.8.0-55-generic-x86_64-with-debian-bullseye-sid
3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
spacepy=0.2.2
numpy=1.20.3
scipy=1.6.3
matplotlib=3.4.2
```

### Version of SpacePy
version 0.2.2 downloaded from pypi via `pip install spacepy` in a conda environment. Conda version 4.9.2

**Comment by drsteve** [comment] 2021-06-29 21:58
Thanks for the report and apologies for the slow response.
I can reproduce the error in our current development version, but I haven't had the time to figure out why yet.

I'm flagging this as a bug and will try to work out where this is happening.
As a possible work around I guess there are two options...
1. as you've documented, you can call something known to work as a dummy call prior to doing the calculations you want. That's far from ideal but will work.
2. we're currently evaluating a Python-based coordinate transform backend, (#296 , and it's not approved for merge yet, so there's no guarantee things won't change in that branch on its way to being merged). If you wanted to use that instead then you can grab the source code by downloading https://github.com/drsteve/spacepy/archive/refs/heads/update-coords.zip, unzipping and installing with `python setup.py install`. The only difference in calling syntax is that to use the new backend you'd add the `use_irbem` keyword argument: `cvals = sc.Coords([[1., 2., 4.]], 'GSM', 'car', use_irbem=False)`
    Using a provisional branch is obviously also far from ideal, although the new backend will give higher accuracy transforms.

Hopefully I'll have a resolution for this soon and both the bug will be fixed and the alternate backend will be finalized and merged.

**Comment by drsteve** [comment] 2021-06-29 23:27
Notes on where the bug might actually be here...

There's nothing in the Python code (`coordinates.py`, `irbempy.py`) that would explain this. So I jumped to calling the f2py-wrapped routine `coord_trans1`, which is what is being called under the hood after some data management:
```
import numpy as np
import spacepy.irbempy as ib
ib.oplib.coord_trans1(2, 4, 2002, 33, 43200, np.asarray([1., 2., 4.]))
```
Output was `array([nan, nan, nan])`

Which narrows things down to either the Fortran library, how it's getting wrapped, something in the compilation, etc.

So I loaded the shared object library freshly compiled from the main branch of PRBEM/IRBEM with ctypes to call the routine manually. This has the benefit of not being the `.so` that spacepy built and wrapped.
```
import ctypes
from ctypes import byref as br
from ctypes import c_int as ci
import numpy as np
posin = (ctypes.c_double * 3)()
posout = (ctypes.c_double * 3)()
posin[0] = 1; posin[1] = 2; posin[2] = 4
ilib = ctypes.cdll.LoadLibrary('github/IRBEM/source/onera_desp_lib_linux_x86_64.so')
ilib.coord_trans1_(br(ci(2)), br(ci(4)), br(ci(2002)), br(ci(33)), br(ci(43200)), br(posin), br(posout))
np.asarray(posout)
```
Output: `array([nan, nan, nan])`

So right now I'm also going to tag this as an upstream error. I'll keep working on it and if it turns out it's not upstream then I'll fix it here. If it is a problem upstream then I'll try to fix in IRBEM and update the version that SpacePy wraps.

**Closed** 2021-08-19 19:59 UTC
Labels: bug, upstream
